export const SET_CONFIG = 'SET_CONFIG';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_HEADER_BACKGROUND_COLOR = 'SET_HEADER_BACKGROUND_COLOR';
export const SET_TITLE_STATE = 'SET_TITLE_STATE';
