// todo remove suppression on multiple exports
// eslint-disable-next-line import/prefer-default-export

export const CoordState = {
  foundWord: false,
  isTriSymOfAFound: false,
  isTriSymOfCFound: false,
  isSqSymOfAFound: false,
  isSqSymOfBFound: false,
  isSqSymOfCFound: false,
  isSqSymOfDFound: false,
  isWordFound: false,
  symOfAFound: false,
  symOfBFound: false,
  symOfCFound: false,
  symOfDFound: false,
  sqSymOfAFound: false,
  sqSymOfBFound: false,
  sqSymOfDFound: false,
  swicthCase: false,
  triCoordA: [{ x: 0, y: 13 }],
  triCoordB: [{ x: 5, y: 0 }],
  triCoordC: [{ x: 3, y: 5 }],
  triCoordA_PRIM: [{ x: 3, y: 5 }],
  triCoordB_PRIM: [{ x: 7, y: 4 }],
  triCoordC_PRIM: [{ x: 3, y: 5 }],
  sqCoordA: [{ x: 1, y: 5 }],
  sqCoordB: [{ x: 2, y: 8 }],
  sqCoordC: [{ x: 5, y: 4 }],
  sqCoordD: [{ x: 7, y: 12 }],
  sqCoordA_PRIM: [{ x: 2, y: 12 }],
  sqCoordB_PRIM: [{ x: 11, y: 3 }],
  sqCoordC_PRIM: [{ x: 4, y: 8 }],
  sqCoordD_PRIM: [{ x: 45, y: 12 }],
  polyCoordA: [{ x: 9, y: 54 }],
  polyCoordB: [{ x: 42, y: 11 }],
  polyCoordC: [{ x: 11, y: 34 }],
  polyCoordD: [{ x: 45, y: 7.5 }],
  polyCoordE: [{ x: 66, y: 11 }],
};

export default CoordState;
